(function () {
  "use strict";

  window.ENERGY_DATA = {
    constants: {
      importDemandMbd: 4.85,
      nationalConsumptionMbd: 5.32,
      domesticProductionMbd: 0.47,
      sprCoverDays: 9.5,
      baseBrentUsd: 86,
      rupeePerUsd: 83.2,
      pumpPassThrough: 0.56,
      inflationSensitivity: 0.028,
      gdpSensitivity: 0.012,
      maxDrawdownMbd: 0.72,
      emergencyStockFloorDays: 2.2,
      refineryRunBaseline: 92
    },

    presets: {
      baseline: {
        hormuzSeverity: 22,
        redSeaSeverity: 18,
        sanctionsPressure: 24,
        opecCut: 3,
        tankerTightness: 18,
        brentMove: 2,
        text: "Routine maritime security warnings in the Persian Gulf. Tanker availability is adequate, Brent is range-bound, and Indian refiners continue term lifting with small spot adjustments."
      },
      hormuz: {
        hormuzSeverity: 72,
        redSeaSeverity: 25,
        sanctionsPressure: 50,
        opecCut: 5,
        tankerTightness: 56,
        brentMove: 13,
        text: "Naval alert and insurance notices indicate a partial closure risk around the Strait of Hormuz. Several Gulf cargoes are delayed, war-risk premiums are rising, and refiners are seeking replacement barrels."
      },
      redsea: {
        hormuzSeverity: 28,
        redSeaSeverity: 78,
        sanctionsPressure: 30,
        opecCut: 2,
        tankerTightness: 49,
        brentMove: 9,
        text: "Houthi attacks force more tankers away from Red Sea and Suez lanes. India-bound West African and Atlantic Basin flows face longer Cape routing, higher freight, and port bunching."
      },
      sanctions: {
        hormuzSeverity: 38,
        redSeaSeverity: 22,
        sanctionsPressure: 82,
        opecCut: 4,
        tankerTightness: 44,
        brentMove: 11,
        text: "Renewed sanctions enforcement targets shadow fleet activity and Iranian-linked shipments. Middle East sour crude availability tightens and spot sour premiums rise."
      },
      triple: {
        hormuzSeverity: 86,
        redSeaSeverity: 70,
        sanctionsPressure: 77,
        opecCut: 12,
        tankerTightness: 82,
        brentMove: 21,
        text: "Compound Gulf shock: US-Iran standoff escalates, Hormuz transits slow, sanctions enforcement increases, Houthi Red Sea attacks continue, and OPEC+ signals an emergency supply cut."
      }
    },

    corridors: [
      {
        id: "hormuz",
        name: "Hormuz Gulf Corridor",
        importShare: 0.43,
        baseRisk: 0.29,
        baseDays: 7,
        congestion: 0.31,
        reroutePenaltyDays: 14,
        x1: 335,
        y1: 194,
        x2: 705,
        y2: 238,
        exposure: {
          hormuzSeverity: 0.94,
          redSeaSeverity: 0.08,
          sanctionsPressure: 0.48,
          opecCut: 0.43,
          tankerTightness: 0.35,
          brentMove: 0.18
        }
      },
      {
        id: "redsea",
        name: "Red Sea / Suez Corridor",
        importShare: 0.11,
        baseRisk: 0.24,
        baseDays: 18,
        congestion: 0.38,
        reroutePenaltyDays: 10,
        x1: 250,
        y1: 154,
        x2: 693,
        y2: 248,
        exposure: {
          hormuzSeverity: 0.08,
          redSeaSeverity: 0.92,
          sanctionsPressure: 0.17,
          opecCut: 0.08,
          tankerTightness: 0.46,
          brentMove: 0.16
        }
      },
      {
        id: "russia",
        name: "Russia / Black Sea Corridor",
        importShare: 0.31,
        baseRisk: 0.36,
        baseDays: 23,
        congestion: 0.29,
        reroutePenaltyDays: 8,
        x1: 230,
        y1: 72,
        x2: 690,
        y2: 232,
        exposure: {
          hormuzSeverity: 0.04,
          redSeaSeverity: 0.26,
          sanctionsPressure: 0.72,
          opecCut: 0.12,
          tankerTightness: 0.38,
          brentMove: 0.21
        }
      },
      {
        id: "atlantic",
        name: "Atlantic Basin / Cape Corridor",
        importShare: 0.10,
        baseRisk: 0.18,
        baseDays: 31,
        congestion: 0.24,
        reroutePenaltyDays: 4,
        x1: 120,
        y1: 270,
        x2: 704,
        y2: 272,
        exposure: {
          hormuzSeverity: 0.02,
          redSeaSeverity: 0.34,
          sanctionsPressure: 0.08,
          opecCut: 0.04,
          tankerTightness: 0.44,
          brentMove: 0.19
        }
      },
      {
        id: "asean",
        name: "ASEAN / East Route",
        importShare: 0.05,
        baseRisk: 0.16,
        baseDays: 10,
        congestion: 0.21,
        reroutePenaltyDays: 3,
        x1: 814,
        y1: 302,
        x2: 752,
        y2: 288,
        exposure: {
          hormuzSeverity: 0.05,
          redSeaSeverity: 0.03,
          sanctionsPressure: 0.05,
          opecCut: 0.08,
          tankerTightness: 0.29,
          brentMove: 0.12
        }
      }
    ],

    suppliers: [
      {
        id: "iraq-basra",
        name: "Iraq Basra Medium",
        country: "Iraq",
        corridor: "hormuz",
        normalMbd: 0.96,
        spareMbd: 0.18,
        api: 29,
        sulfur: 3.1,
        family: "medium sour",
        basePremium: 1.4,
        reliability: 0.68,
        opecExposure: 0.76,
        sanctionsExposure: 0.18,
        loadingPort: "Basra",
        indiaPort: "Mundra / Vadinar"
      },
      {
        id: "saudi-arab-light",
        name: "Saudi Arab Light",
        country: "Saudi Arabia",
        corridor: "hormuz",
        normalMbd: 0.72,
        spareMbd: 0.24,
        api: 33,
        sulfur: 1.8,
        family: "light sour",
        basePremium: 2.1,
        reliability: 0.79,
        opecExposure: 0.88,
        sanctionsExposure: 0.12,
        loadingPort: "Ras Tanura",
        indiaPort: "Jamnagar / Mangalore"
      },
      {
        id: "uae-murban",
        name: "UAE Murban",
        country: "UAE",
        corridor: "hormuz",
        normalMbd: 0.46,
        spareMbd: 0.22,
        api: 40,
        sulfur: 0.8,
        family: "light sweet",
        basePremium: 3.7,
        reliability: 0.82,
        opecExposure: 0.66,
        sanctionsExposure: 0.08,
        loadingPort: "Fujairah / Jebel Dhanna",
        indiaPort: "Mangalore / Kochi"
      },
      {
        id: "kuwait-export",
        name: "Kuwait Export",
        country: "Kuwait",
        corridor: "hormuz",
        normalMbd: 0.31,
        spareMbd: 0.09,
        api: 31,
        sulfur: 2.5,
        family: "medium sour",
        basePremium: 1.8,
        reliability: 0.72,
        opecExposure: 0.8,
        sanctionsExposure: 0.1,
        loadingPort: "Mina Al Ahmadi",
        indiaPort: "Paradip / Chennai"
      },
      {
        id: "russia-urals",
        name: "Russia Urals",
        country: "Russia",
        corridor: "russia",
        normalMbd: 1.34,
        spareMbd: 0.27,
        api: 31,
        sulfur: 1.6,
        family: "medium sour",
        basePremium: -3.2,
        reliability: 0.58,
        opecExposure: 0.05,
        sanctionsExposure: 0.82,
        loadingPort: "Primorsk / Novorossiysk",
        indiaPort: "Sikka / Paradip"
      },
      {
        id: "nigeria-bonny",
        name: "Nigeria Bonny Light",
        country: "Nigeria",
        corridor: "atlantic",
        normalMbd: 0.16,
        spareMbd: 0.18,
        api: 35,
        sulfur: 0.2,
        family: "light sweet",
        basePremium: 4.6,
        reliability: 0.54,
        opecExposure: 0.44,
        sanctionsExposure: 0.04,
        loadingPort: "Bonny",
        indiaPort: "Mundra / Kochi"
      },
      {
        id: "angola-girassol",
        name: "Angola Girassol",
        country: "Angola",
        corridor: "atlantic",
        normalMbd: 0.11,
        spareMbd: 0.14,
        api: 31,
        sulfur: 0.3,
        family: "medium sweet",
        basePremium: 3.2,
        reliability: 0.61,
        opecExposure: 0.34,
        sanctionsExposure: 0.02,
        loadingPort: "Luanda",
        indiaPort: "Mangalore / Vadinar"
      },
      {
        id: "brazil-lula",
        name: "Brazil Lula",
        country: "Brazil",
        corridor: "atlantic",
        normalMbd: 0.08,
        spareMbd: 0.21,
        api: 29,
        sulfur: 0.3,
        family: "medium sweet",
        basePremium: 2.6,
        reliability: 0.7,
        opecExposure: 0,
        sanctionsExposure: 0,
        loadingPort: "Santos",
        indiaPort: "Mundra / Kochi"
      },
      {
        id: "guyana-liza",
        name: "Guyana Liza",
        country: "Guyana",
        corridor: "atlantic",
        normalMbd: 0.04,
        spareMbd: 0.16,
        api: 32,
        sulfur: 0.6,
        family: "medium sweet",
        basePremium: 4.0,
        reliability: 0.74,
        opecExposure: 0,
        sanctionsExposure: 0,
        loadingPort: "Liza FPSO",
        indiaPort: "Sikka / Mangalore"
      },
      {
        id: "us-mars",
        name: "US Mars / WTI Blend",
        country: "United States",
        corridor: "atlantic",
        normalMbd: 0.12,
        spareMbd: 0.24,
        api: 31,
        sulfur: 1.9,
        family: "medium sour",
        basePremium: 5.4,
        reliability: 0.82,
        opecExposure: 0,
        sanctionsExposure: 0,
        loadingPort: "US Gulf",
        indiaPort: "Mundra / Paradip"
      },
      {
        id: "malaysia-tapis",
        name: "Malaysia Tapis Blend",
        country: "Malaysia",
        corridor: "asean",
        normalMbd: 0.05,
        spareMbd: 0.05,
        api: 43,
        sulfur: 0.1,
        family: "light sweet",
        basePremium: 6.8,
        reliability: 0.78,
        opecExposure: 0,
        sanctionsExposure: 0,
        loadingPort: "Kerteh",
        indiaPort: "Chennai / Kochi"
      }
    ],

    refineries: [
      {
        id: "jamnagar",
        name: "Jamnagar",
        state: "Gujarat",
        capacityMbd: 1.36,
        complexity: 0.94,
        sourTolerance: 0.91,
        lightSweetNeed: 0.2,
        x: 720,
        y: 230
      },
      {
        id: "vadinar",
        name: "Vadinar",
        state: "Gujarat",
        capacityMbd: 0.41,
        complexity: 0.86,
        sourTolerance: 0.82,
        lightSweetNeed: 0.24,
        x: 735,
        y: 238
      },
      {
        id: "mangalore",
        name: "Mangalore",
        state: "Karnataka",
        capacityMbd: 0.31,
        complexity: 0.7,
        sourTolerance: 0.64,
        lightSweetNeed: 0.38,
        x: 747,
        y: 287
      },
      {
        id: "kochi",
        name: "Kochi",
        state: "Kerala",
        capacityMbd: 0.31,
        complexity: 0.73,
        sourTolerance: 0.59,
        lightSweetNeed: 0.42,
        x: 762,
        y: 316
      },
      {
        id: "paradip",
        name: "Paradip",
        state: "Odisha",
        capacityMbd: 0.3,
        complexity: 0.79,
        sourTolerance: 0.76,
        lightSweetNeed: 0.26,
        x: 820,
        y: 268
      },
      {
        id: "panipat",
        name: "Panipat",
        state: "Haryana",
        capacityMbd: 0.3,
        complexity: 0.72,
        sourTolerance: 0.66,
        lightSweetNeed: 0.34,
        x: 772,
        y: 195
      },
      {
        id: "chennai",
        name: "Chennai",
        state: "Tamil Nadu",
        capacityMbd: 0.21,
        complexity: 0.61,
        sourTolerance: 0.52,
        lightSweetNeed: 0.48,
        x: 794,
        y: 312
      },
      {
        id: "visakh",
        name: "Visakhapatnam",
        state: "Andhra Pradesh",
        capacityMbd: 0.3,
        complexity: 0.68,
        sourTolerance: 0.6,
        lightSweetNeed: 0.38,
        x: 810,
        y: 286
      }
    ]
  };
})();
